pharma_project:
  outputs:
    dev:
      type: postgres
      host: 34.163.120.6
      user: pharma_user
      password: salgado
      dbname: pharma_data_engineering
      schema: dev
      port: 5432
      threads: 4
    uat:
      type: postgres
      host: 34.163.120.6
      user: pharma_user
      password: salgado
      dbname: pharma_data_engineering
      schema: uat
      port: 5432
      threads: 4
# TODO: modify prod db connection
    prod:
      type: postgres
      host: 34.163.120.6
      user: pharma_user
      password: salgado
      dbname: pharma_data_engineering
      schema: prod
      port: 5432
      threads: 4
  target: dev
