pharma_project:
  outputs:
    dev:
      type: postgres
      host: 34.163.27.186
      user: pharma_user
      password: salgado
      dbname: pharma_data_engineering
      schema: dev
      port: 5432
      threads: 16
    uat:
      type: postgres
      host: 34.163.27.186
      user: pharma_user
      password: salgado
      dbname: pharma_data_engineering
      schema: uat
      port: 5432
      threads: 16
    prod:
      type: postgres
      host: 34.163.27.186
      user: pharma_user
      password: salgado
      dbname: pharma_data_engineering
      schema: prod
      port: 5432
      threads: 16
  target: uat
