{{
  config(
    materialized = 'table',
    indexes=[
      {'columns': ['doc_id']}
    ]
  )
}}

select
    -- Base data
    b.*,
    -- Labels
    l.labelHtml,
    l.label,
    l.long_label,
    l.type_label,
    l.short_label,
    l.search_label,
    l.long_label_html,
    l.short_label_html,
    -- Codes
    c.cip7,
    c.cip13,
    c.cip13_referent,
    c.cis,
    c.ucd7,
    c.ean13,
    c.ucd13,
    c.code13Referent,
    -- Properties
    p.product_name,
    p.product_dosage,
    p.galenic_form_code,
    p.galenic_form_label,
    p.aspect,
    p.thumbnail,
    p.subLaboratories,
    p.inFacilityFormulary,
    p.galenicFormLabelHtml,
    p.segmentationAttributes,
    p.intake_units,
    -- Flags
    f.is_homeo,
    f.is_doping,
    f.is_generic,
    f.is_internal,
    f.is_narcotic,
    f.is_referent,
    f.is_crushable,
    f.is_biosimilar,
    f.is_pediatrics,
    f.hybrid,
    f.drive_warning,
    f.medicalDevice,
    f.hospitalDelivery,
    f.exactcureSimulable,
    f.is_ghs,
    f.is_vaccin,
    f.needs_fridge,
    f.needs_freezer,
    f.mte,
    f.t2a,
    f.tfr,
    f.horsGhs,
    f.testReagent,
    f.abortionDrug,
    f.firstAgeMilk,
    f.anticoagulant,
    f.drugException,
    f.hybridReferent,
    f.soluteDilution,
    f.bloodDerivative,
    f.deconditionning,
    f.humanAntibiotic,
    f.communityApproval,
    f.biosimilarReferent,
    f.minorContraceptive,
    f.pregnancyPictogram,
    f.seasonalFluVaccine,
    f.infertilityTreatment,
    f.reinforcedMonitoring,
    f.veterinaryAntibiotic,
    f.mindalteringSubstance,
    f.emergencyContraceptive,
    f.veterinaryPrescription,
    -- Extended Info
    e.marketing_authorization_date,
    e.marketing_authorization_end_date,
    e.marketing_start_date,
    e.marketing_end_date,
    e.last_marketing_status_change_date,
    e.marketing_authorization_status,
    e.marketing_authorization_procedure,
    e.marketing_authorization_number,
    e.european_authorization_number,
    e.marketing_status,
    e.atc_code,
    e.dci,
    e.shape,
    e.route,
    e.holder,
    e.status,
    e.dosage_text,
    e.indication,
    e.laboratory,
    e.composition,
    e.description,
    e.presentation,
    e.prescription_conditions,
    e.reimbursement_rate,
    e.reimbursement_collectivity,
    e.reimbursement_security_social,
    e.hospital_price,
    e.reference_price,
    e.public_price,
    e.risk_level,
    e.substance_level,
    e.prescription_level

from {{ ref('stg_api_service_base') }} b
left join {{ ref('stg_api_service_labels') }} l using (doc_id)
left join {{ ref('stg_api_service_codes') }} c using (doc_id)
left join {{ ref('stg_api_service_properties') }} p using (doc_id)
left join {{ ref('stg_api_service_flags') }} f using (doc_id)
left join {{ ref('stg_api_service_extended_info') }} e using (doc_id) 