{{
  config(
    materialized = 'table',
    indexes=[
      {'columns': ['doc_id']}
    ]
  )
}}

select
    id,
    doc->>'_id' as doc_id,
    doc->'raw_data'->'prices'->>'tfr' as prices_tfr,
    -- Raw data
    doc->'raw_data'->'deletedDate' as deletedDate,
    doc->'raw_data'->'searchProperties' as searchProperties,
    -- extendedProperties
    doc->'raw_data'->'extendedProperties'->'sam' as sam,
    doc->'raw_data'->'extendedProperties'->'photo' as photo,
    doc->'raw_data'->'extendedProperties'->'actCode' as actCode,
    doc->'raw_data'->'extendedProperties'->'ammDate' as ammDate,
    doc->'raw_data'->'extendedProperties'->'listCode' as listCode,
    doc->'raw_data'->'extendedProperties'->'segments' as segments,
    doc->'raw_data'->'extendedProperties'->'segmentsHtml' as segmentsHtml,
    doc->'raw_data'->'extendedProperties'->'ammNumber' as ammNumber,
    doc->'raw_data'->'extendedProperties'->'ammRevisionDate' as ammRevisionDate,
    doc->'raw_data'->'extendedProperties'->'commonNameLabel' as commonNameLabel,
    doc->'raw_data'->'extendedProperties'->'paradocChapters' as paradocChapters,
    doc->'raw_data'->'extendedProperties'->'virtualDrugCode' as virtualDrugCode,
    doc->'raw_data'->'extendedProperties'->'equivalentDosage' as equivalentDosage,
    doc->'raw_data'->'extendedProperties'->'virtualDrugLabel' as virtualDrugLabel,
    doc->'raw_data'->'extendedProperties'->'segmentationStatus' as segmentationStatus,
    doc->'raw_data'->'extendedProperties'->'segmentationStatusHtml' as segmentationStatusHtml,
    doc->'raw_data'->'extendedProperties'->'biosimilarGroupLabel' as biosimilarGroupLabel,
    doc->'raw_data'->'extendedProperties'->'replacementProductId' as replacementProductId,
    doc->'raw_data'->'extendedProperties'->'replacementProductLabel' as replacementProductLabel,
    doc->'raw_data'->'extendedProperties'->'brandCode' as brandCode,
    doc->'raw_data'->'extendedProperties'->'brandLabel' as brandLabel,
    doc->'raw_data'->'extendedProperties'->'brandLabelHtml' as brandLabelHtml,
    doc->'raw_data'->'extendedProperties'->'listLabel' as listLabel,
    doc->'raw_data'->'extendedProperties'->'rangeCode' as rangeCode,
    doc->'raw_data'->'extendedProperties'->'rangeLabel' as rangeLabel,
    doc->'raw_data'->'extendedProperties'->'rangeLabelHtml' as rangeLabelHtml,
    doc->'raw_data'->'extendedProperties'->'statusCode' as statusCode,
    doc->'raw_data'->'extendedProperties'->'statusLabel' as statusLabel,
    doc->'raw_data'->'extendedProperties'->'actLabelHtml' as actLabelHtml,
    doc->'raw_data'->'extendedProperties'->'creationDate' as creationDate,
    doc->'raw_data'->'extendedProperties'->'numberOfUcds' as numberOfUcds,
    doc->'raw_data'->'extendedProperties'->'revisionDate' as revisionDate,
    doc->'raw_data'->'extendedProperties'->'commonNameCode' as commonNameCode,
    doc->'raw_data'->'extendedProperties'->'identifier'->'packagingLabel' as packagingLabel,
    doc->'raw_data'->'extendedProperties'->'identifier'->'presentationLabel' as presentationLabel,
    doc->'raw_data'->'extendedProperties'->'identifier'->'unitsPerPresentation' as unitsPerPresentation,
    doc->'raw_data'->'extendedProperties'->'identifier'->'numberOfPresentations' as numberOfPresentations,
    doc->'raw_data'->'extendedProperties'->'identifier'->'unitPresentationLabel' as unitPresentationLabel,
    doc->'raw_data'->'extendedProperties'->'identifier'->'unitPresentationLabelPlural' as unitPresentationLabelPlural,
    doc->'raw_data'->'extendedProperties'->'crushability'->'openable' as openable,
    doc->'raw_data'->'extendedProperties'->'crushability'->'crushable' as crushable,
    doc->'raw_data'->'extendedProperties'->'crushability'->'informations' as informations,
    doc->'raw_data'->'extendedProperties'->'crushability'->'unpleasantTaste' as unpleasantTaste,
    doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithMilk' as canBeTakenWithMilk,
    doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithWater' as canBeTakenWithWater,
    doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithYogurt' as canBeTakenWithYogurt,
    doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithCompote' as canBeTakenWithCompote,
    doc->'raw_data'->'extendedProperties'->'crushability'->'disintegrationPossible' as disintegrationPossible,
    doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithOrangeJuice' as canBeTakenWithOrangeJuice,
    doc->'raw_data'->'extendedProperties'->'crushability'->'immediateMedicationPossible' as immediateMedicationPossible,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'nurse' as prescriptibles_nurse,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'doctor' as prescriptibles_doctor,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'dentist' as prescriptibles_dentist,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'biologist' as prescriptibles_biologist,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'orthoptist' as prescriptibles_orthoptist,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'pharmacist' as prescriptibles_pharmacist,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'podiatrist' as prescriptibles_podiatrist,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'veterinary' as prescriptibles_veterinary,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'midwifeForWomen' as prescriptibles_midwifeForWomen,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'physiotherapist' as prescriptibles_physiotherapist,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'speechTherapist' as prescriptibles_speechTherapist,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'doctormidwifeForPatient' as prescriptibles_midwifeForPatient,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'midwifeForNewborns' as prescriptibles_midwifeForNewborns,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'advancedPracticeNurse' as prescriptibles_advancedPracticeNurse,
    doc->'raw_data'->'extendedProperties'->'prescriptibles'->'occupationalTherapist' as prescriptibles_occupationalTherapist,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'fax' as holderLab_fax,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'code' as holderLab_code,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'town' as holderLab_town,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'label' as holderLab_label,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'phone' as holderLab_phone,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'address' as holderLab_address,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'country' as holderLab_country,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'website' as holderLab_website,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'zipCode' as holderLab_zipCode,
    doc->'raw_data'->'extendedProperties'->'holderLab'->'email' as holderLab_email,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'fax' as operatingLab_fax,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'code' as operatingLab_code,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'town' as operatingLab_town,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'label' as operatingLab_label,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'phone' as operatingLab_phone,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'address' as operatingLab_address,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'country' as operatingLab_country,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'website' as operatingLab_website,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'zipCode' as operatingLab_zipCode,
    doc->'raw_data'->'extendedProperties'->'operatingLab'->'email' as operatingLab_email,
    -- Dates
    (doc->>'extracted_date')::timestamp as extracted_date,
    (doc->>'deleted')::boolean as is_deleted
from {{ source('pharma_sources', 'mycollection') }} 