{{
  config(
    materialized = 'table',
    indexes=[
      {'columns': ['doc_id']},
      {'columns': ['code']},
      {'columns': ['code13']}
    ]
  )
}}

with source as (
    select * from {{ source('pharma_sources', 'mycollection') }}
),

extracted as (
    select
        id,
        doc->>'_id' as doc_id,
        doc->>'code' as code,
        (doc->>'type')::integer as type,
        doc->>'code13' as code13,
        doc->>'productId' as productId,
        -- Labels
        doc->'labelHtml' as labelHtml,
        doc->'labels'->>'label' as label,
        doc->'labels'->>'longLabel' as long_label,
        doc->'labels'->>'typeLabel' as type_label,
        doc->'labels'->>'shortLabel' as short_label,
        doc->'labels'->>'searchLabel' as search_label,
        doc->'labels'->>'longLabelHtml' as long_label_html,
        doc->'labels'->>'shortLabelHtml' as short_label_html,
        
        -- Properties
        doc->'properties'->'codes'->>'cip7' as cip7,
        doc->'properties'->'codes'->>'cip13' as cip13,
        doc->'properties'->'codes'->>'cip13Referent' as cip13_referent,
        doc->'properties'->'codes'->>'cis' as cis,
        doc->'properties'->'codes'->>'ucd7' as ucd7,
        doc->'properties'->'codes'->>'ean13' as ean13,
        doc->'properties'->'codes'->>'ucd13' as ucd13,
        doc->'properties'->'codes'->>'code13Referent' as code13Referent,
        doc->'properties'->>'productName' as product_name,
        doc->'properties'->>'productDosage' as product_dosage,
        doc->'properties'->>'galenicFormCode' as galenic_form_code,
        doc->'properties'->>'galenicFormLabel' as galenic_form_label,
        doc->'properties'->>'aspect' as aspect,
        doc->'properties'->>'thumbnail' as thumbnail,
        doc->'properties'->>'subLaboratories' as subLaboratories,
        doc->'properties'->>'inFacilityFormulary' as inFacilityFormulary,
        doc->'properties'->>'galenicFormLabelHtml' as galenicFormLabelHtml,
        doc->'properties'->>'segmentationAttributes' as segmentationAttributes,
        -- Flags
        (doc->'properties'->'flags'->>'homeo')::integer as is_homeo,
        (doc->'properties'->'flags'->>'doping')::integer as is_doping,
        (doc->'properties'->'flags'->>'generic')::integer as is_generic,
        (doc->'properties'->'flags'->>'internal')::integer as is_internal,
        (doc->'properties'->'flags'->>'narcotic')::integer as is_narcotic,
        (doc->'properties'->'flags'->>'referent')::integer as is_referent,
        (doc->'properties'->'flags'->>'crushable')::integer as is_crushable,
        (doc->'properties'->'flags'->>'biosimilar')::integer as is_biosimilar,
        (doc->'properties'->'flags'->>'pediatrics')::integer as is_pediatrics,
        (doc->'properties'->'flags'->>'hybrid')::integer as hybrid,
        doc->'properties'->'flags'->>'driveWarning' as drive_warning,
        doc->'properties'->'flags'->>'medicalDevice' as medicalDevice,
        doc->'properties'->'flags'->>'hospitalDelivery' as hospitalDelivery,
        doc->'properties'->'flags'->>'exactcureSimulable' as exactcureSimulable,
        -- Extended Flags
        (doc->'properties'->'flags'->'extendedFlags'->>'ghs')::integer as is_ghs,
        (doc->'properties'->'flags'->'extendedFlags'->>'vaccin')::integer as is_vaccin,
        (doc->'properties'->'flags'->'extendedFlags'->>'fridge')::integer as needs_fridge,
        (doc->'properties'->'flags'->'extendedFlags'->>'freezer')::integer as needs_freezer,
        (doc->'properties'->'flags'->'extendedFlags'->>'mte')::integer as mte,
        (doc->'properties'->'flags'->'extendedFlags'->>'t2a')::integer as t2a,
        (doc->'properties'->'flags'->'extendedFlags'->>'tfr')::integer as tfr,
        (doc->'properties'->'flags'->'extendedFlags'->>'horsGhs')::integer as horsGhs,
        (doc->'properties'->'flags'->'extendedFlags'->>'testReagent')::integer as testReagent,
        (doc->'properties'->'flags'->'extendedFlags'->>'abortionDrug')::integer as abortionDrug,
        (doc->'properties'->'flags'->'extendedFlags'->>'firstAgeMilk')::integer as firstAgeMilk,
        (doc->'properties'->'flags'->'extendedFlags'->>'anticoagulant')::integer as anticoagulant,
        (doc->'properties'->'flags'->'extendedFlags'->>'drugException')::integer as drugException,
        (doc->'properties'->'flags'->'extendedFlags'->>'hybridReferent')::integer as hybridReferent,
        (doc->'properties'->'flags'->'extendedFlags'->>'soluteDilution')::integer as soluteDilution,
        (doc->'properties'->'flags'->'extendedFlags'->>'bloodDerivative')::integer as bloodDerivative,
        (doc->'properties'->'flags'->'extendedFlags'->>'deconditionning')::integer as deconditionning,
        (doc->'properties'->'flags'->'extendedFlags'->>'humanAntibiotic')::integer as humanAntibiotic,
        (doc->'properties'->'flags'->'extendedFlags'->>'mcommunityApprovalte')::integer as communityApproval,
        (doc->'properties'->'flags'->'extendedFlags'->>'biosimilarReferent')::integer as biosimilarReferent,
        (doc->'properties'->'flags'->'extendedFlags'->>'minorContraceptive')::integer as minorContraceptive,
        (doc->'properties'->'flags'->'extendedFlags'->>'pregnancyPictogram')::integer as pregnancyPictogram,
        (doc->'properties'->'flags'->'extendedFlags'->>'seasonalFluVaccine')::integer as seasonalFluVaccine,
        (doc->'properties'->'flags'->'extendedFlags'->>'infertilityTreatment')::integer as infertilityTreatment,
        (doc->'properties'->'flags'->'extendedFlags'->>'reinforcedMonitoring')::integer as reinforcedMonitoring,
        (doc->'properties'->'flags'->'extendedFlags'->>'veterinaryAntibiotic')::integer as veterinaryAntibiotic,
        (doc->'properties'->'flags'->'extendedFlags'->>'mindalteringSubstance')::integer as mindalteringSubstance,
        (doc->'properties'->'flags'->'extendedFlags'->>'emergencyContraceptive')::integer as emergencyContraceptive,
        (doc->'properties'->'flags'->'extendedFlags'->>'veterinaryPrescription')::integer as veterinaryPrescription,
        -- Intake Units
        doc->'properties'->'intakeUnits' as intake_units,
        -- Prices
        doc->'raw_data'->'prices'->>'tfr' as prices_tfr,
        doc->'raw_data'->'prices'->>'vatRate' as vatRate,
        doc->'raw_data'->'prices'->>'ucdPrice' as ucdPrice,
        doc->'raw_data'->'prices'->>'sellingPrice' as sellingPrice,
        doc->'raw_data'->'prices'->>'repaymentRate' as repaymentRate,
        doc->'raw_data'->'prices'->>'reimbursementBase' as reimbursementBase,
        -- Raw data
        doc->'raw_data'->'deletedDate' as deletedDate,
        doc->'raw_data'->'searchProperties' as searchProperties,
        -- extendedProperties
        doc->'raw_data'->'extendedProperties'->'sam' as sam,
        doc->'raw_data'->'extendedProperties'->'photo' as photo,
        doc->'raw_data'->'extendedProperties'->'actCode' as actCode,
        doc->'raw_data'->'extendedProperties'->'ammDate' as ammDate,
        doc->'raw_data'->'extendedProperties'->'listCode' as listCode,
        doc->'raw_data'->'extendedProperties'->'segments' as segments,
        doc->'raw_data'->'extendedProperties'->'segmentsHtml' as segmentsHtml,
        doc->'raw_data'->'extendedProperties'->'ammNumber' as ammNumber,
        doc->'raw_data'->'extendedProperties'->'ammRevisionDate' as ammRevisionDate,
        doc->'raw_data'->'extendedProperties'->'commonNameLabel' as commonNameLabel,
        doc->'raw_data'->'extendedProperties'->'paradocChapters' as paradocChapters,
        doc->'raw_data'->'extendedProperties'->'virtualDrugCode' as virtualDrugCode,
        doc->'raw_data'->'extendedProperties'->'equivalentDosage' as equivalentDosage,
        doc->'raw_data'->'extendedProperties'->'virtualDrugLabel' as virtualDrugLabel,
        doc->'raw_data'->'extendedProperties'->'segmentationStatus' as segmentationStatus,
        doc->'raw_data'->'extendedProperties'->'segmentationStatusHtml' as segmentationStatusHtml,
        doc->'raw_data'->'extendedProperties'->'biosimilarGroupLabel' as biosimilarGroupLabel,
        doc->'raw_data'->'extendedProperties'->'replacementProductId' as replacementProductId,
        doc->'raw_data'->'extendedProperties'->'replacementProductLabel' as replacementProductLabel,
        doc->'raw_data'->'extendedProperties'->'brandCode' as brandCode,
        doc->'raw_data'->'extendedProperties'->'brandLabel' as brandLabel,
        doc->'raw_data'->'extendedProperties'->'brandLabelHtml' as brandLabelHtml,
        doc->'raw_data'->'extendedProperties'->'listLabel' as listLabel,
        doc->'raw_data'->'extendedProperties'->'rangeCode' as rangeCode,
        doc->'raw_data'->'extendedProperties'->'rangeLabel' as rangeLabel,
        doc->'raw_data'->'extendedProperties'->'rangeLabelHtml' as rangeLabelHtml,
        doc->'raw_data'->'extendedProperties'->'statusCode' as statusCode,
        doc->'raw_data'->'extendedProperties'->'statusLabel' as statusLabel,
        doc->'raw_data'->'extendedProperties'->'actLabelHtml' as actLabelHtml,
        doc->'raw_data'->'extendedProperties'->'creationDate' as creationDate,
        doc->'raw_data'->'extendedProperties'->'numberOfUcds' as numberOfUcds,
        doc->'raw_data'->'extendedProperties'->'revisionDate' as revisionDate,
        doc->'raw_data'->'extendedProperties'->'commonNameCode' as commonNameCode,
        doc->'raw_data'->'extendedProperties'->'identifier'->'packagingLabel' as packagingLabel,
        doc->'raw_data'->'extendedProperties'->'identifier'->'presentationLabel' as presentationLabel,
        doc->'raw_data'->'extendedProperties'->'identifier'->'unitsPerPresentation' as unitsPerPresentation,
        doc->'raw_data'->'extendedProperties'->'identifier'->'numberOfPresentations' as numberOfPresentations,
        doc->'raw_data'->'extendedProperties'->'identifier'->'unitPresentationLabel' as unitPresentationLabel,
        doc->'raw_data'->'extendedProperties'->'identifier'->'unitPresentationLabelPlural' as unitPresentationLabelPlural,
        doc->'raw_data'->'extendedProperties'->'crushability'->'openable' as openable,
        doc->'raw_data'->'extendedProperties'->'crushability'->'crushable' as crushable,
        doc->'raw_data'->'extendedProperties'->'crushability'->'informations' as informations,
        doc->'raw_data'->'extendedProperties'->'crushability'->'unpleasantTaste' as unpleasantTaste,
        doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithMilk' as canBeTakenWithMilk,
        doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithWater' as canBeTakenWithWater,
        doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithYogurt' as canBeTakenWithYogurt,
        doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithCompote' as canBeTakenWithCompote,
        doc->'raw_data'->'extendedProperties'->'crushability'->'disintegrationPossible' as disintegrationPossible,
        doc->'raw_data'->'extendedProperties'->'crushability'->'canBeTakenWithOrangeJuice' as canBeTakenWithOrangeJuice,
        doc->'raw_data'->'extendedProperties'->'crushability'->'immediateMedicationPossible' as immediateMedicationPossible,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'nurse' as prescriptibles_nurse,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'doctor' as prescriptibles_doctor,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'dentist' as prescriptibles_dentist,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'biologist' as prescriptibles_biologist,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'orthoptist' as prescriptibles_orthoptist,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'pharmacist' as prescriptibles_pharmacist,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'podiatrist' as prescriptibles_podiatrist,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'veterinary' as prescriptibles_veterinary,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'midwifeForWomen' as prescriptibles_midwifeForWomen,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'physiotherapist' as prescriptibles_physiotherapist,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'speechTherapist' as prescriptibles_speechTherapist,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'doctormidwifeForPatient' as prescriptibles_midwifeForPatient,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'midwifeForNewborns' as prescriptibles_midwifeForNewborns,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'advancedPracticeNurse' as prescriptibles_advancedPracticeNurse,
        doc->'raw_data'->'extendedProperties'->'prescriptibles'->'occupationalTherapist' as prescriptibles_occupationalTherapist,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'fax' as holderLab_fax,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'code' as holderLab_code,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'town' as holderLab_town,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'label' as holderLab_label,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'phone' as holderLab_phone,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'address' as holderLab_address,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'country' as holderLab_country,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'website' as holderLab_website,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'zipCode' as holderLab_zipCode,
        doc->'raw_data'->'extendedProperties'->'holderLab'->'email' as holderLab_email,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'fax' as operatingLab_fax,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'code' as operatingLab_code,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'town' as operatingLab_town,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'label' as operatingLab_label,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'phone' as operatingLab_phone,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'address' as operatingLab_address,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'country' as operatingLab_country,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'website' as operatingLab_website,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'zipCode' as operatingLab_zipCode,
        doc->'raw_data'->'extendedProperties'->'operatingLab'->'email' as operatingLab_email,
        -- Dates
        (doc->>'extracted_date')::timestamp as extracted_date,
        (doc->>'deleted')::boolean as is_deleted
    from source
)

select * from extracted 