name: dbt Airflow CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with GCP Artifact Registry
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow:latest
            europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow:${{ github.sha }}
          build-args: |
            PYTHON_VERSION=3.12

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs delete dbt-airflow-job --region=europe-west9 --quiet || true
          gcloud run jobs create dbt-airflow-job \
            --image=${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow:latest \
            --region=${{ secrets.GCP_REGION }} \
            --task-timeout=3600 \
            --set-env-vars="DBT_PROFILE=${{ secrets.DBT_PROFILE }}" \
            --set-env-vars="TARGET_ENV=uat" \
            --args="dbt run --target uat --exclude staging.curated.stg_similarity_scores_categorie_taxonomy"

  deploy-airflow-dags:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync DAGs to Cloud Storage
        run: |
          gcloud storage cp -r airflow/dags gs://${{ secrets.AIRFLOW_BUCKET }}/
      
      - name: Restart Airflow on VM
        run: |
          gcloud compute ssh ${{ secrets.GCP_SA_EMAIL }}@${{ secrets.UAT_VM_NAME }} \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --command "sudo systemctl restart airflow-scheduler && sudo systemctl restart airflow-webserver"