name: DBT + Airflow CI/CD

on:
  push:
    branches:
      - "**" # Toutes les branches
  pull_request:
    branches:
      - develop
  release:
    types: [created]

jobs:
  deploy-dev:
    environment: dev
    if: github.event_name == 'push' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Generate DBT profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          pharma_project:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${{ vars.VM_NAME }}
                user: ${{ vars.DBT_USER }}
                password: ${{ secrets.DBT_PWD }}
                dbname: ${{ vars.DBT_DB }}
                schema: dev
                port: 5432
                threads: 16
          EOF

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev
          docker build -t europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-dev:latest .
          docker push europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-dev:latest

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs delete dbt-airflow-job-dev --region=${{ vars.GCP_REGION }} --quiet || true
          gcloud run jobs create dbt-airflow-job-dev \
            --image=europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-dev:latest \
            --region=${{ vars.GCP_REGION }} \
            --task-timeout=3600 \
            --set-env-vars TARGET_ENV=dev \
            --args="dbt run --target dev --exclude staging.curated.int_similarity_scores_categorie_taxonomy"

      - name: Sync DAGs to Cloud Storage
        run: |
          gcloud storage cp -r airflow/dags gs://${{ vars.AIRFLOW_BUCKET }}/

      - name: Restart Airflow on VM
        run: |
          gcloud compute ssh ${{ vars.GCP_SA_EMAIL }}@${{ vars.VM_NAME }} \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --zone ${{ vars.GCP_ZONE }} \
            --command "sudo systemctl restart airflow-scheduler && sudo systemctl restart airflow-webserver"

  deploy-uat:
    environment: staging
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Generate DBT profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          pharma_project:
            target: uat
            outputs:
              uat:
                type: postgres
                host: ${{ vars.VM_NAME }}
                user: ${{ vars.DBT_USER }}
                password: ${{ secrets.DBT_PWD }}
                dbname: ${{ vars.DBT_DB }}
                schema: uat
                port: 5432
                threads: 16
          EOF

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev
          docker build -t europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-uat:latest .
          docker push europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-uat:latest

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs delete dbt-airflow-job-uat --region=${{ vars.GCP_REGION }} --quiet || true
          gcloud run jobs create dbt-airflow-job-uat \
            --image=europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-uat:latest \
            --region=${{ vars.GCP_REGION }} \
            --task-timeout=3600 \
            --set-env-vars TARGET_ENV=uat \
            --args="dbt run --target uat --exclude staging.curated.int_similarity_scores_categorie_taxonomy"

      - name: Sync DAGs to Cloud Storage
        run: |
          gcloud storage cp -r airflow/dags gs://${{ vars.AIRFLOW_BUCKET }}/

      - name: Restart Airflow on VM
        run: |
          gcloud compute ssh ${{ vars.GCP_SA_EMAIL }}@${{ vars.VM_NAME }} \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --zone ${{ vars.GCP_ZONE }} \
            --command "sudo systemctl restart airflow-scheduler && sudo systemctl restart airflow-webserver"

  deploy-prod:
    environment: prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Generate DBT profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          pharma_project:
            target: prod
            outputs:
              prod:
                type: postgres
                host: ${{ vars.VM_NAME }}
                user: ${{ vars.DBT_USER }}
                password: ${{ secrets.DBT_PWD }}
                dbname: ${{ vars.DBT_DB }}
                schema: prod
                port: 5432
                threads: 16
          EOF

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev
          docker build -t europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-prod:latest .
          docker push europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-prod:latest

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs delete dbt-airflow-job-prod --region=${{ vars.GCP_REGION }} --quiet || true
          gcloud run jobs create dbt-airflow-job-prod \
            --image=europe-west9-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/dbt-airflow-prod:latest \
            --region=${{ vars.GCP_REGION }} \
            --task-timeout=3600 \
            --set-env-vars TARGET_ENV=prod \
            --args="dbt run --target prod"

      - name: Sync DAGs to Cloud Storage
        run: |
          gcloud storage cp -r airflow/dags gs://${{ vars.AIRFLOW_BUCKET }}/

      - name: Restart Airflow on VM
        run: |
          gcloud compute ssh ${{ vars.GCP_SA_EMAIL }}@${{ vars.VM_NAME }} \
            --project ${{ vars.GCP_PROJECT_ID }} \
            --zone ${{ vars.GCP_ZONE }} \
            --command "sudo systemctl restart airflow-scheduler && sudo systemctl restart airflow-webserver"
