name: Build and Deploy DBT Job

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharma-dbt-job:latest .
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharma-dbt-job:latest

      # Deploy Cloud Run Job
      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs delete pharma-dbt-job --region=europe-west9 --quiet || true
          gcloud run jobs create pharma-dbt-job \
            --image=${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharma-dbt-job:latest \
            --region=${{ secrets.GCP_REGION }} \
            --task-timeout=3600 \
            --set-env-vars="DBT_PROFILE=${{ secrets.DBT_PROFILE }}" \
            --args="dbt run --target uat --exclude intermediate.inter_similarity_scores_categorie_taxonomy"
